---
- name: Deploy Flask App on EC2
  hosts: web
  become: yes

  tasks:

    - name: Update system packages
      shell: yum update -y

    - name: Install Python3 and pip
      shell: yum install -y python3 python3-pip

    - name: Install Docker
      shell: amazon-linux-extras install docker -y

    - name: Start Docker service
      shell: systemctl start docker

    - name: Enable Docker service
      shell: systemctl enable docker

    - name: Add ec2-user to docker group
      shell: usermod -aG docker ec2-user

    - name: Install Docker SDK for Python
      shell: pip3 install docker

    - name: Reset SSH connection
      meta: reset_connection

    - name: Pull Docker image
      shell: docker pull annie237/flask-capstone:latest

    - name: Run Flask container
      shell: |
        docker rm -f flask-app || true
        docker run -d --name flask-app -p 5000:5000 annie237/flask-capstone:latest